import discord
from discord.ext import commands
import io
import os

from src.core.ai_services.comfyui_client import ComfyUIClient
from src.core.ai_services.ollama_client import OllamaClient
from src.core.ai_services.xtts_client import XTTSClient
from src.config import VOICE_PATHS

OLLAMA_MODEL = "dolphin-2.2.1-mistral:7b-q4_K_M"

class Creative(commands.Cog):
    """
    Contains commands for creative generation (art, text, etc.).
    """
    def __init__(self, bot):
        self.bot = bot
        self.comfyui_client = ComfyUIClient()
        self.ollama_client = OllamaClient()
        self.xtts_client = XTTSClient()

    @commands.command(name="imagine", help="Generate an image from a text prompt. Usage: !imagine <prompt>")
    @commands.cooldown(1, 60, commands.BucketType.user)
    async def imagine(self, ctx, *, prompt: str):
        """Generates an image based on a text prompt using ComfyUI."""
        await ctx.message.add_reaction("🎨")

        try:
            comfy_prompt = self.comfyui_client.create_simple_text_to_image_prompt(prompt)
            images = self.comfyui_client.queue_prompt(comfy_prompt)

            if images:
                image = images[0]
                with io.BytesIO() as image_binary:
                    image.save(image_binary, 'PNG')
                    image_binary.seek(0)

                    embed = discord.Embed(title="Creation Complete", description=f"**Prompt:**\n> {prompt}", color=0x2ECC71)
                    embed.set_image(url="attachment://generated_image.png")
                    embed.set_footer(text=f"Generated by {ctx.author.display_name}")

                    await ctx.send(file=discord.File(fp=image_binary, filename="generated_image.png"), embed=embed)
            else:
                await ctx.send(f":x: **Error:** Image generation failed. The ComfyUI server might be busy or an error occurred.")

        except Exception as e:
            print(f"Error during !imagine command: {e}")
            await ctx.send(f":x: **Fatal Error:** Could not connect to the ComfyUI server. Please ensure it is running correctly.")
        finally:
            await ctx.message.remove_reaction("🎨", self.bot.user)

    @commands.command(name="write", help="Generate a story or text from a prompt. Usage: !write <prompt>")
    @commands.cooldown(1, 45, commands.BucketType.user)
    async def write(self, ctx, *, prompt: str):
        """Generates text based on a prompt using Ollama."""
        await ctx.message.add_reaction("✍️")

        try:
            system_prompt = "You are a helpful assistant."
            if hasattr(ctx.message, 'persona'):
                system_prompt = ctx.message.persona.base_persona

            generated_text = self.ollama_client.generate_text(OLLAMA_MODEL, prompt, system_prompt)

            if "Error:" not in generated_text:
                response_text = generated_text
                if len(generated_text) > 1900:
                    response_text = generated_text[:1900] + "\n\n... (output truncated)"

                embed = discord.Embed(title=f"Story by {ctx.author.display_name}", description=response_text, color=0x3498DB)
                embed.add_field(name="Original Prompt", value=f"> {prompt}", inline=False)
                await ctx.send(embed=embed)
            else:
                await ctx.send(f":x: **Error:** {generated_text}")

        except Exception as e:
            print(f"Error during !write command: {e}")
            await ctx.send(f":x: **Fatal Error:** An unexpected error occurred with the text generation server.")
        finally:
            await ctx.message.remove_reaction("✍️", self.bot.user)

    @commands.command(name="speak", help="Generate speech from text using the bot's persona voice. Usage: !speak <text>")
    @commands.cooldown(1, 30, commands.BucketType.user)
    async def speak(self, ctx, *, text: str):
        """Generates speech from text using the bot's persona voice."""
        if not hasattr(ctx.message, 'persona'):
            return await ctx.send(":x: This command is intended for bot personas to use.")

        persona = ctx.message.persona
        await ctx.message.add_reaction("🔊")

        try:
            speaker_wav_path = VOICE_PATHS.get(persona.name.upper())
            if not speaker_wav_path or not os.path.exists(speaker_wav_path):
                await ctx.send(f"_{persona.name} tries to speak, but their voice cannot be found. The Master has not yet granted them this gift._")
                await ctx.message.remove_reaction("🔊", self.bot.user)
                return

            audio_data = self.xtts_client.generate_speech(text, speaker_wav_path)

            if audio_data:
                await ctx.send(f"**{persona.name} says:**", file=discord.File(fp=audio_data, filename="speech.wav"))
            else:
                await ctx.send(f"_{persona.name} tries to speak, but the words catch in their throat. The XTTSv2 server may be offline._")
        except Exception as e:
            print(f"Error during !speak command: {e}")
            await ctx.send(f":x: **Fatal Error:** An unexpected error occurred with the speech generation server.")
        finally:
            await ctx.message.remove_reaction("🔊", self.bot.user)

    @imagine.error
    @write.error
    @speak.error
    async def command_error(self, ctx, error):
        if isinstance(error, commands.CommandOnCooldown):
            await ctx.send(f":hourglass: This command is on cooldown. Please try again in {error.retry_after:.2f} seconds.")
        else:
            await ctx.send(f":x: An unexpected error occurred: {error}")

async def setup(bot):
    """Adds the cog to the bot."""
    await bot.add_cog(Creative(bot))