import discord
from discord.ext import commands
import io
import os
import asyncio
from src.config import get_voice_path

OLLAMA_MODEL = "dolphin-2.2.1-mistral:7b-q4_K_M"

class Creative(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(name="imagine", help="Generate an image from a text prompt.")
    @commands.cooldown(1, 60, commands.BucketType.user)
    async def imagine(self, ctx, *, prompt: str):
        await ctx.message.add_reaction("🎨")
        try:
            from src.core.ai_services.comfyui_client import ComfyUIClient
            images = ComfyUIClient().queue_prompt(ComfyUIClient().create_simple_text_to_image_prompt(prompt))
            if images:
                with io.BytesIO() as image_binary:
                    images[0].save(image_binary, 'PNG')
                    image_binary.seek(0)
                    embed = discord.Embed(title="Creation Complete", description=f"**Prompt:**\n> {prompt}", color=0x2ECC71)
                    embed.set_image(url="attachment://generated_image.png")
                    embed.set_footer(text=f"Generated by {ctx.author.display_name}")
                    await ctx.send(file=discord.File(fp=image_binary, filename="generated_image.png"), embed=embed)
            else:
                await ctx.send(f":x: Image generation failed.")
        except Exception:
            await ctx.send(f":x: Could not connect to the ComfyUI server.")
        finally:
            await ctx.message.remove_reaction("🎨", self.bot.user)

    @commands.command(name="write", help="Generate a story or text from a prompt.")
    @commands.cooldown(1, 45, commands.BucketType.user)
    async def write(self, ctx, *, prompt: str):
        await ctx.message.add_reaction("✍️")
        try:
            generated_text = self.bot.ollama_client.generate_text(OLLAMA_MODEL, prompt)
            if "Error:" not in generated_text:
                response_text = generated_text[:1900] + "..." if len(generated_text) > 1900 else generated_text
                embed = discord.Embed(title=f"Story by {ctx.author.display_name}", description=response_text, color=0x3498DB)
                embed.add_field(name="Original Prompt", value=f"> {prompt}", inline=False)
                await ctx.send(embed=embed)
            else:
                await ctx.send(f":x: {generated_text}")
        except Exception:
            await ctx.send(f":x: An unexpected error occurred with the text generation server.")
        finally:
            await ctx.message.remove_reaction("✍️", self.bot.user)

    @commands.command(name="speak", help="Make a character speak text in your voice channel.")
    @commands.cooldown(1, 30, commands.BucketType.user)
    async def speak(self, ctx, character_name: str, *, text: str):
        if not ctx.author.voice:
            return await ctx.send("You must be in a voice channel to use this command.")
        persona = self.bot.persona_manager.get_persona(character_name)
        if not persona:
            return await ctx.send(f"Character '{character_name}' not found.")
        voice_path = get_voice_path(persona.name)
        if not voice_path or not os.path.exists(voice_path):
            return await ctx.send(f"Voice file for '{character_name}' not found in .env configuration.")

        await ctx.message.add_reaction("🔊")
        try:
            audio_data = self.bot.xtts_client.generate_speech(text, voice_path)
            if not audio_data:
                return await ctx.send(f"Could not generate speech. The XTTS server may be offline or misconfigured.")

            vc = discord.utils.get(self.bot.voice_clients, guild=ctx.guild)
            if vc and vc.is_connected():
                await vc.move_to(ctx.author.voice.channel)
            else:
                vc = await ctx.author.voice.channel.connect()

            vc.play(discord.FFmpegPCMAudio(io.BytesIO(audio_data), pipe=True))
            while vc.is_playing():
                await asyncio.sleep(1)
            await vc.disconnect()
        except Exception as e:
            await ctx.send(f":x: An error occurred during speech playback: {e}")
        finally:
            await ctx.message.remove_reaction("🔊", self.bot.user)

    async def cog_command_error(self, ctx, error):
        if isinstance(error, commands.CommandOnCooldown):
            await ctx.send(f":hourglass: Command on cooldown. Try again in {error.retry_after:.2f}s.")
        else:
            await ctx.send(f":x: An unexpected error occurred: {error}")

async def setup(bot):
    await bot.add_cog(Creative(bot))